---
- name: ssh configuration
  hosts: managed1
  vars:
    group_name: devops
    group_users:
      - eissa
      - ahmed
      - mirna
  tasks:
    - name: create {{group_name}} group
      ansible.builtin.group:
        name: "{{group_name}}"
        state: present
        gid: 1300

    - name: create users and append them to the {{group_name}} group
      ansible.builtin.user:
        name: "{{item}}"
        groups: "{{group_name}}"
        create_home: yes
        append: yes
        state: present
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/{{item}}_id_rsa
      loop: "{{group_users}}" 

    - name: setup key-based authentication
      ansible.posix.authorized_key:
        user: "{{item}}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      loop: "{{group_users}}"

    - name: setting sudoers from fresh users
      ansible.builtin.lineinfile:
        dest: /etc/sudoers.d/{{item}}
        line: "{{item}} ALL=(ALL) NOPASSWD: ALL"
        owner: root
        group: root
        mode: '0440'
        create: yes
      loop: "{{group_users}}"

