---                           
- name: installing httpd when state is defined
  ansible.builtin.yum:           
    name: httpd                  
    state: "{{state}}"
  register: stete_check
  when: state is defined