---
# tasks file for roles/web
- name: first task - install httpd
  ansible.builtin.yum:
    name: "{{ package_name }}"
    state: present

- name: second task - start and enable httpd
  ansible.builtin.service:
    name: "{{ service_name }}"
    state: started
    enabled: yes

- name: third task - copying index.j2 to hosts
  ansible.builtin.template:
    src: index.j2
    dest: /var/www/html/index.html
  notify: web_changed
